### ISSUE TITLE
vanilla l1 loss

### ISSUE THREAD

**Issue by weidalin** [WangWenhao0716/Adapted-Center-and-Scale-Prediction#11]
请问可以提供vanilla l1 loss那部分的代码吗？

**Comment by WangWenhao0716** [comment]
nn.L1Loss(reduce=False, size_average=False)
就是vanilla l1 loss

**Comment by weidalin** [comment]
> nn.L1Loss(reduce=False, size_average=False)
> 就是vanilla l1 loss
