### ISSUE TITLE
指标提不上去

### ISSUE THREAD

**Issue by Gs928** [WangWenhao0716/Adapted-Center-and-Scale-Prediction#16]
我也采用了batchsize=4进行训练，但是最终指标只达到了11.50%左右，有什么别的训练tricks吗

**Comment by WangWenhao0716** [comment]
是用的我的源代码吗？不经过任何改动那种

**Comment by Gs928** [comment]
是的，使用的完全是源代码。最新的训练结果大概在10.5%左右。和源码不同的是batchsize=4是使用了4张显卡，一张显卡上一个batch

**Comment by WangWenhao0716** [comment]
batchsize=4是使用了4张显卡，一张显卡上一个batch
这个是不行的，我这个对应的论文里有实验报告

**Comment by Gs928** [comment]
好的，谢谢
