### ISSUE TITLE
loss is decreasing very slooowly during training

### ISSUE THREAD

**Issue by kakusikun** [WangWenhao0716/Adapted-Center-and-Scale-Prediction#2]
Does the loss decrease very slowly?

I made some modification myself, 
change the model, 4 GPUs, each batch size of 16, Adam, lr 1e-4 * 2 

I found that the change of loss decreased very sloooowly. especially the focal loss.

Did you have the same phenomenon like this?

Could you share what you meet?

**Comment by WangWenhao0716** [comment]
Why did you change the model? This may cause poorer performance. And how do you define "slow"? I think a model that can be trained within one day is fast enough.

**Comment by kakusikun** [comment]
I change model since resnet does not meet my requirement.

Let me put the question another way,
how low is the value of focal loss when you think the training is done, w/o multiply 0.01?

**Comment by WangWenhao0716** [comment]
The training process is finished when the performance is no longer improved. It has nothing to do with how big the loss is.



发自我的iPhone


------------------ Original ------------------

**Comment by kakusikun** [comment]
I just wanna check the correctness in my implementation, hence, the loss might be a signal for me.

Thanks for your reply.

**Comment by WangWenhao0716** [comment]
OK Please give me a email, I may send my training process document to you if I can still find it because the time is too long.



发自我的iPhone


------------------ Original ------------------
