### ISSUE TITLE
The value of weight in Figure.3?

### ISSUE THREAD

**Issue by Ning5195** [WangWenhao0716/Adapted-Center-and-Scale-Prediction#8]
When output the parameters of ACSP(Vanilla L1).pth. 
For example, the value of mean_weight and var_weight are shown as follows:

layer3.17.sn3.mean_weight : [ 1.5857, -0.8275, -0.7425]
layer3.17.sn3.var_weight : [-1.3445,  0.1184,  1.1824]

Is this the weight in Figure.3? If so, how did you calculate the proportion?
Why the sum of mean_weight or var_weight is 0 not 1?
I think I misunderstood, but I don't know the right answer.
Could you please give me an explanation?
Thank you for your help!

**Comment by WangWenhao0716** [comment]
It may be:
aIN + bLN + cBN,
then:
a/(a+b+c)
and so on...

Now, I do not think this explanation is meaningful. Please do not study this paper.

**Comment by Ning5195** [comment]
Thank you for your answer.
Does it mean, for example:
1.5857/(1.5857-0.8275-0.7425)
or
1.5857/(1.5857+0.8275+0.7425)

By the way, the paper is really concise and helpful.

**Comment by WangWenhao0716** [comment]
Maybe it is not right. Please refer to https://arxiv.org/pdf/1907.10473.pdf, Fig. 4.

**Comment by Ning5195** [comment]
Both 1.5857/(1.5857-0.8275-0.7425) and 1.5857/(1.5857+0.8275+0.7425) are wrong?
All right.
Thank you for your answer!
Have a good day!

**Comment by WangWenhao0716** [comment]
OK! I think both of them are wrong.
